name: chat_gate_ai
description: "Ghat Gate AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  # Freezed
  freezed_annotation: ^3.1.0
  # Navigation
  go_router: ^17.0.0
  # Settings
  shared_preferences: ^2.5.3
  # Google Sign In
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  google_sign_in_ios: ^6.2.3
  # URL Launcher
  url_launcher: ^6.3.2
  # WebView
  flutter_inappwebview: ^6.1.5
  # YouTube video player
  youtube_player_iframe: ^5.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

  build_runner: ^2.7.1
  analyzer: ^7.6.0
  # Flutter gen
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0
  # Riverpod
  riverpod_generator: ^3.0.3
  # riverpod_lint: ^3.0.3
  # custom_lint: ^0.8.1
  # Freezed
  freezed: ^3.2.3
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

flutter_gen:
  line_length: 100

flutter_intl:
  enabled: true
